defaultContentLanguage     = 'zh-tw'
baseURL                    = 'https://kuaz.info/'
languageCode               = 'zh-tw'
title                      = 'Chiawei Chen | 陳家瑋'
theme                      = 'ivy'
enableEmoji                = true
hasCJKLanguage             = true
rssLimit                   = 10
footnoteReturnLinkContents = '↩'

[permalinks]
    posts = '/posts/:year/:month/:slug'

[languages]
[languages.zh-tw]
    contentDir = 'content/zh-tw'
    title        = '陳家瑋'
    languageCode = 'zh-tw'
    languageName = '中文'
    weight       = 1
[languages.en]
    contentDir = 'content/en'
    title        = 'Chiawei Chen'
    languageCode = 'en'
    languageName = 'English'
    weight       = 2
