[highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'xcode'
    tabWidth           = 4

[goldmark]
[goldmark.extensions]
    definitionList  = true
    footnote        = true
    linkify         = true
    linkifyProtocol = 'https'
    strikethrough   = true
    table           = true
    taskList        = true
    typographer     = true
[goldmark.parser]
    autoHeadingID                      = true
    autoHeadingIDType                  = 'github'
    wrapStandAloneImageWithinParagraph = true
[goldmark.parser.attribute]
    block = false
    title = true
[goldmark.renderer]
    hardWraps = false
    unsafe    = false
    xhtml     = false
