[[main]]
    identifier = 'home'
    name       = '首頁'
    url        = '/'
    weight     = 1

[[main]]
    identifier = 'posts'
    name       = '文章'
    url        = '/posts'
    weight     = 2

[[main]]
    identifier = 'memo'
    name       = '備忘'
    url        = '/en/memo'
    weight     = 3

[[main]]
    identifier = 'vitae'
    name       = '簡歷'
    url        = '/vitae'
    weight     = 98

[[main]]
    identifier = 'about'
    name       = '關於'
    url        = '/about'
    weight     = 99

[[main]]
    identifier = 'recipes'
    name       = '食譜'
    url        = '/recipes'
    weight     = 4

[[main]]
    identifier = 'en'
    name       = 'EN'
    url        = '/en'
    weight     = 100
