[[main]]
    identifier = 'home'
    name       = '首頁'
    url        = '/'
    weight     = 1

[[main]]
    identifier = 'posts'
    name       = '文章'
    url        = '/posts'
    weight     = 2

[[main]]
    identifier = 'memo'
    name       = '備忘'
    url        = '/memo'
    weight     = 3

[[main]]
    identifier = 'vitae'
    name       = '簡歷'
    url        = '/vitae'
    weight     = 98

[[main]]
    identifier = 'about'
    name       = '關於'
    url        = '/about'
    weight     = 99

[[main]]
    identifier = 'zhtw'
    name       = '中文'
    url        = '../'
    weight     = 100
