[[main]]
    identifier = 'home'
    name       = '首頁'
    url        = '/'
    weight     = 1

[[main]]
    identifier = 'about'
    name       = '關於'
    url        = '/about'
    weight     = 2

[[main]]
    identifier = 'zhtw'
    name       = '中文'
    url        = '../'
    weight     = 3
