footer         = '&copy; [Chiawei Chen](/) 2021 - {{< year >}}'
dataRepo       = 'exkuretrol/kuaz.info'
dataRepoId     = 'MDEwOlJlcG9zaXRvcnkzODMwNzQ5Nzk='
dataCategory   = 'Announcements'
dataCategoryId = 'DIC_kwDOFtVCo84CTvcz'
