baseURL = "http://example.org/"
languageCode = "en-us"
title = "Site"
theme = "ivy"
[permalinks]
	"posts" = "/posts/:year/:month/:slug"


[menu]

	[[menu.main]]
		  name = "Home"
		  url = "/"
			weight = 1
